apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: py-github-quay-10dec-gitops
  description: This is GitOps manifest for py-github-quay-10dec   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: py-github-quay-10dec
    backstage.io/kubernetes-id: py-github-quay-10dec 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: py-github-quay-10dec   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:py-github-quay-10dec
